name: cfdi_elements
description: Librería para contener las estructuras de datos que componen un cfdi.
version: 1.0.0
homepage: https://github.com/dartcfdi/cfdi_elements
repository: https://github.com/dartcfdi/cfdi_elements
issue_tracker: https://github.com/dartcfdi/cfdi_elements/issues

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - CFDI
  - SAT
  - Mexican Invoice
  - xml

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  xml: ^6.5.0

dev_dependencies:
  args: ^2.4.2
  lint: ^2.3.0
  path: ^1.9.0
  recase: ^4.1.0
  test: ^1.25.0
